---
server_name: production

digitransit_ui:
  - config: hbnext
    domain: herrenberg.stadtnavi.de
  - config: landstadtmobil
    domain: landstadtmobil.de
    redirects:
      -  www.landstadtmobil.de
  - config: muensingen
    domain: muensingen.landstadtmobil.de
  - config: engstingen
    domain: engstingen.landstadtmobil.de
  - config: ludwigsburg
    domain: ludwigsburg.stadtnavi.eu

otp_docker_tag: 2022-03-16-11_29
otp_router_config: herrenberg/router-config.json

digitransit:
  images:
    otp: mfdz/opentripplanner:{{ otp_docker_tag }}
    ui: stadtnavi/digitransit-ui:73a8c906a21c9b5fc90ee6ff4c21f07296862b5f
    map_server: stadtnavi/hsl-map-server:95b2b9fa2e748c839d8cb4bfaf0b6ef7fdbad1d8
    fares_service: stadtnavi/fares-service:5b14aa8d7951bfdedac626d73556b0a75aa7a874

api_hostname: api.stadtnavi.de
matomo_hostname: track.stadtnavi.de

certbot_certs:
  - domains:
    - "{{ digitransit_ui[0].domain }}"
  - domains:
    - "{{ digitransit_ui[1].domain }}"
  - domains:
    - "{{ digitransit_ui[1].redirects[0] }}"
  - domains:
    - "{{ digitransit_ui[2].domain }}"
  - domains:
    - "{{ digitransit_ui[3].domain }}"
  - domains:
    - "{{ digitransit_ui[4].domain }}"
  - domains:
    - "{{ api_hostname }}"
  - domains:
    - "{{ matomo_hostname }}"

certbot_admin_email: mail@leonard.io

matomo_url: https://track.stadtnavi.de/js/container_uzMuZE7B.js

encryption_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34323964326233643932303161613837376463333566336131356236643962356339333962396261
          3162303239323566323434643236393335353330343339330a333662373764666336393436363931
          33636337353066616466323364626462373564643262393761646264343339373339316239323266
          3662643530306537610a316536393936396439346465323766303332343831633630333939343036
          65656462383263636330343538343030623966386661383339363864613436626438333836366639
          64363465313630386335666266663764633561633432373137346434306362666334656363373565
          61623132386262613137613666353235363435343938306635383561376561653739393965376634
          34353363373336383032656131316433366263666431393461643636653637326131633230656135
          62623865643537653333656333373137346635306265386361663236333639633866313838636538
          36636365366635373664393563326363356361363237353133313238396463323733303664326334
          653336653034653430383666303935616234

matomo_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35363437316434326263393362346661303433373161373663363133623839623135373637356462
          3131336562376332353534303437353735363737663866360a353839356461376438343862663162
          38336362333862383039666232343165653532626136356335636661633361343333326431333830
          6130323266363332370a396531346461353837643430366233376339653239313961336535646439
          31613563373337663566363631386663346332643339623432343634623935363933353832323939
          3466643534303934626365653563343033306261373761656537

matomo_db_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35396632386434643139626138323862323935633436383834336136373831303432633335663434
          3830363538643664306566623931643330356439356138650a323661313864636461323965383137
          63313364353563313266356231613737363135393935393938623733336633653132343833313233
          6564396164373933370a626537306130633433326233383334653632663933333565383138646232
          35396430373233643231323237326330636333663538313830323363643231616634396133643530
          6461636662353639373262666133373239336433646437306264

