---
- name: Check nginx conf
  command: "/usr/sbin/nginx -t"
  become: yes
  listen: "Restart nginx"

- name: Restart nginx service
  service:
    name: nginx
    state: restarted
  listen: "Restart nginx"
